### PR TITLE
Add support for SQS

### PR DESCRIPTION
**Pull request by djanowski**
Includes #53, but that one can be reviewed independently.

### CODE REVIEW

**Comment by assaf** [comment]
Code changes over extend what the PR title suggests

**Comment by djanowski** [comment]
I thought looking at the big picture would be valuable. Except for #53, do you want me to update the PR name or split SQS and SNS into separate PRs?

**Comment by assaf** [comment]
+1 on big picture, but easier to review smaller PR

**Comment by djanowski** [comment]
#54.

**Pull request closed without merging**
