### PR TITLE
No need to account for `error` being undefined, `_connect` takes care.

### PR DESCRIPTION
**Pull request by djanowski**

### CODE REVIEW

**Comment by assaf** [comment]
How does `_connect` take care of the Socket events?

**Comment by djanowski** [comment]
https://github.com/assaf/ironium/blob/master/src/queues.js#L180-L182 ?

**Comment by assaf** [comment]
If there's an error/close event on the connection, then lines 180/182 will reject the promise. No connection, lines 107/108 (in `request`) never execute, no event listener attached.

If there's no error/close event on the connection, then line 178 resolves the promise, `request` method gets a connection and registers event listeners. The `close` event has no arguments, so `onConnectionEnd` called with `undefined`.

**Comment by djanowski** [comment]
Correct, sorry about that.

**Pull request closed without merging**
